name: Checkmarx SAST Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.4 #Github Action version
      with:
        project: test-cxflow # <-- Insert Checkmarx SAST Project Name
        team: test-cxflow
        checkmarx_url: https://checkmarx.snpd.io/ # To be stored in GitHub Secrets.
        checkmarx_username: cxflow # To be stored in GitHub Secrets.
        checkmarx_password: vfu4dzg2pau.CZD3fwx # To be stored in GitHub Secrets.
        checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C # To be stored in GitHub Secrets.
        break_build: false
        scanners: sast
        bug_tracker: Sarif
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --cx-flow.filterSeverity --cx-flow.filterCategory
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif
